---
- name: Create a folder
  ansible.builtin.file:
    path:  "{{ run_dir }}"
    state: directory
    
- name: Define architecture mapping
  ansible.builtin.set_fact:
    arch_mapping:
      x86_64: "x64"
      aarch64: "arm64"
      arm64: "arm64"

- name: Def architecture
  ansible.builtin.set_fact:
    arch: "{{ arch_mapping[ansible_architecture]}}"
 
- name: Fetch GitHub releases page
  ansible.builtin.uri:
    url: "https://api.github.com/repos/actions/runner/releases/latest"
    return_content: yes
  register: github_releases

- name: Extract download URL for architecture
  ansible.builtin.set_fact:
    runner_download_url: >-
      {{
        (github_releases.json.assets | selectattr('browser_download_url', 'search', 'actions-runner-linux-' ~ arch))
        | map(attribute='browser_download_url') | list | first
      }}

- name: Set regex
  ansible.builtin.set_fact:
    regex: "linux-{{ arch }} -->([A-Za-z0-9]*?)<!--" 

- name: Extract relative checksum
  ansible.builtin.set_fact:
    checksum: "{{ github_releases.json.body | regex_search(regex, '\\1', multiline=True) }}"
    
- name: Download the latest runner package
  ansible.builtin.get_url:
    url: "{{ runner_download_url }}"
    dest: "{{run_dir}}/actions-runner-linux-{{ arch }}.tar.gz"
    mode: "0774"
    checksum: sha256:{{ checksum }}
 
- name: Extract the installer
  ansible.builtin.unarchive:
    src: "{{run_dir}}/actions-runner-linux-{{ arch }}.tar.gz"
    dest: "{{ run_dir }}"
    remote_src: yes

#TODO add task to got register TOKEN
# https://docs.github.com/en/rest/actions/self-hosted-runners?apiVersion=2022-11-28#create-a-registration-token-for-an-organization
- name: Create the runner and start the configuration experience
  ansible.builtin.command: 
    "./config.sh \
     --url {{ url }} \
     --token {{ token }} \
     --name {{lookup('community.general.random_pet')}} \
     --unattended "
  args:
    chdir: "{{ run_dir }}"
  become: no

- name: install service
  ansible.builtin.command: 
    "./svc.sh install "
  args:
    chdir: "{{ run_dir }}"
  tags: service
  
- name: start service
  ansible.builtin.command: 
    "./svc.sh start "
  args:
    chdir: "{{ run_dir }}"
  tags: service2

