---
main:
  hosts:
    server_main:
      ansible_host: "{{ ip }}"

web:
  hosts:
    server_web:
      ansible_host: "{{ ip }}"


test_web:
  hosts:
    server_test_web:
      ansible_host: "{{ ip }}" 
   
test:
  children:
    test_web:

new:
  children:
    main:
    web:
    test_web:


amd64:
  hosts:
    <ip>

arm64: 
  hosts:
    <ip>

arm:
  hosts:
    <ip>

master:
  hosts:
    <ip>

nodes:
  hosts:
    <ip>

cluster:
  children:
    master:
    nodes:
          
runners:
  children:
    arm64:
